version: '3.1'

services:
  camunda:
    build: .
    environment:
      - WAIT_FOR=camunda-db:5432
      - WAIT_FOR_TIMEOUT=60
    ports:
      - 8080:8080
      - 9999:9999
      - 8000:8000
    depends_on:
      - camunda-db
    links:
      - camunda-db
  camunda-db:
    hostname: camunda-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    expose:
      - 5432
    ports:
      - 5432:5432
